#! /bin/sh -e
check_var(){
   if [ -z $($1) ]; then
   echo "$1 is unset"
   exit 1
else
   return 0
fi
}

echo "checking evn variables"
echo "cloning package manager..."
CC=gcc
current_dir=$(pwd)
DEST_DIR="$current_dir/pine"
git clone https://github.com/kisslinux/kiss.git ./package_man 
export KISS_PATH="$current_dir/temp_repos/core"
echo "creating $DEST_DIR"
mkdir -p $DEST_DIR
echo "cloning repos"
git clone https://github.com/pine-linux/repos temp_repos
export KISS_ROOT=$DEST_DIR
./package_man/kiss b baselayout
./package_man/kiss i baselayout
kiss b sbase
kiss i sbase
kiss b ubase
kiss i ubase
./package_man/kiss b awk
./package_man/kiss i awk
./package_man/kiss b dash
./package_man/kiss i dash
./package_man/kiss b musl
./package_man/kiss i musl
./package_man/kiss b gzip
./package_man/kiss i gzip
./package_man/kiss b libressl
./package_man/kiss i libressl
./package_man/kiss b kiss
./package_man/kiss i kiss
./package_man/kiss b smdev
./package_man/kiss i smdev
./package_man/kiss b shinit
./package_man/kiss i shinit
./package_man/kiss b make
./package_man/kiss i make
./package_man/kiss b tcc
./package_man/kiss i tcc
