#! /bin/sh -e
check_var(){
   if [ -z $($1) ]; then
   echo "$1 is unset"
   exit 1
else
   return 0
fi
}

echo "checking evn variables"
check_var "CC"
check_var "DEST_DIR"
echo "cloning package manager..."
git clone https://github.com/kisslinux/kiss.git ./package_man 
echo "cloning repos"
git clone https://github.com/pine-linux/repos ./repos
echo "creating $DEST_DIR"
mkdir -p DEST_DIR
export KISS_ROOT=$DEST_DIR
echo building musl
./package_man/kiss b musl
./package_man/kiss i musl
echo building the shell
./package_man/kiss b mksh
./package_man/kiss i mksh
echo building gcc
./package_man b gcc
./package_man/kiss i gcc
echo building coreutils
./package_man/kiss b sbase
./package_man/kiss i sbase
./package_man/kiss b ubase
./package_man/kiss i ubase
echo build pkg manager
./package_man/kiss b kiss
./package_man/kiss i kiss


